# themes from https://github.com/alacritty/alacritty-theme
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
